/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef OPENIAB_AUTODEFS_H
#define OPENIAB_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_OPENIAB_NAME "openiab"
#define S3E_EXT_OPENIAB_HASH 0x70e383a3

#ifdef S3E_EXT_REGISTER
#ifndef S3E_EXT_REGISTER_KEY
#define S3E_EXT_REGISTER_KEY(name, num, key) S3E_EXT_REGISTER(name, num)
#endif
S3E_EXT_REGISTER("openiab", 11)
#else

#endif /* S3E_EXT_REGISTER */
#endif /* !OPENIAB_AUTODEFS_H */
